### ISSUE TITLE
Mapear fluxos para design de telas

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#102]
Criação de Fluxo do Usuário
Criação de Wireframes
- [x] Main Page/Como Funciona
- [x] Ranking Mensal/Geral
- [x] Dashboard/Perfil do Usuário
- [ ] Feedback para integrações [Novo]

**Comment by brunomoch-zz** [comment]
Link para acompanhamento:
https://www.figma.com/file/URmifgWMBfyAN6J6MuPISccd/FLUXO?node-id=0%3A1
