### ISSUE TITLE
Ui para tela pós autenticação do Github

### ISSUE THREAD

**Issue by mergulhao** [impulsoteam/atena#114]

**Comment by cenicoemir** [comment]
`Tela de confirmação de autenticação pela primeira vez:`
"Olá novamente, nobre Impulser! Sua dedicação foi posta a prova e você passou com honrarias!"
"A partir de agora você pode desempenhar trabalhos junto aos *nossos* projetos open-source!"
Ainda está em dúvida de como funcionam?! Não tem problema, dá uma olhadinha aqui neste papiro: link"

`Tela de confirmação com erro`
"Ops! parece que você entrou na caverna errada. Que falta faz um GPS, não é? Siga esse caminho e não vai errar: https://github.com/login/oauth/authorize?scope=user:email&client_id=a1e8e0d86d57411ef452&state=UCZCQH7CG"

**Comment by cenicoemir** [comment]
Wireframes das telas montados. 
Link de Acompanhamento: https://www.figma.com/file/URmifgWMBfyAN6J6MuPISccd/FLUXO?node-id=0%3A1

**Comment by cenicoemir** [comment]
Esta tarefa é uma demanda técnica gerada a partir da issue #102, assim sendo o titulo foi ajustado para o real propósito da tarefa.

Foram criados dois wireframes para a autenticação com github.

**Comment by mergulhao** [comment]
@cenicoemir Nesse caso aqui não era pra fazer wireframe. Era pra versão versão final da UI mesmo... Minha expectativa era a entrega completa dessa tela.

**Comment by cenicoemir** [comment]
@mergulhao Então vou dar reopen e puxar de volta.

**Comment by mergulhao** [comment]
@cenicoemir Pode ver com o Bruno (ele já tá aqui no Github?). Pra ele entregar já completinho, se possivel integrado no projeto, senão html+css pro pessoal colocar no código.
