### ISSUE TITLE
UI da tela de "Como Funciona"

### ISSUE THREAD

**Issue by mergulhao** [impulsoteam/atena#115]

**Comment by brunomoch-zz** [comment]
Opção de topo I:
https://xd.adobe.com/view/446d0504-1f66-4ae6-6972-159a4273bde8-325c/?fullscreen

Opção de topo II: 
https://xd.adobe.com/view/1e473915-cb1c-430f-4fe7-4fa4a5fe20f2-6876/?fullscreen

**Comment by cenicoemir** [comment]
Texto final para Tela: https://docs.google.com/document/d/1LnMJH-f6oeEisDUrQk3ilZQiStJPxoKp8HQG16azG9w/edit?usp=sharing

**Comment by brunomoch-zz** [comment]
https://xd.adobe.com/view/e8a9c843-eac3-40e1-4ce4-b5f2919957a9-9e98/screen/26808d77-f18e-4a18-ba0f-c0a7572968ba/home-1280-2
