### ISSUE TITLE
Adicionar termos de uso no Rocket Chat

### ISSUE THREAD

**Issue by mergulhao** [impulsoteam/atena#117]
<img width="1012" alt="screen shot 2018-12-17 at 12 33 29" src="https://user-images.githubusercontent.com/8128/50093524-0e99fa00-01f8-11e9-8292-f1b9fff56273.png">

**Comment by mergulhao** [comment]
O que temos de controle sobre esse conteúdo?

<img width="658" alt="screen shot 2018-12-17 at 12 34 59" src="https://user-images.githubusercontent.com/8128/50093602-42751f80-01f8-11e9-8859-1e15978bdea5.png">

**Comment by cenicoemir** [comment]
Dá para configurar tudo isso no painel administrativo. Vou aceitar a task para inserir esses dados lá, ao mesmo tempo vou envolver o @brunomoch na issue #107 em paralelo para combinar com esta Issue aqui.

**Comment by mergulhao** [comment]
@cenicoemir @rtarantelli Blz! Por hora, pode remover tudo isso que tem nesse footer ae. Não precisamos de english version. Os termos do serviço já estão no app.impulso.network e não temos politica de privacidade ainda. E tb não queremos dizer sobre usarmos a plataforma opensource da rocket (até pq vamos pagar por ela). Então pode remover geral isso ae do footer e deixar sem nada.

**Comment by mergulhao** [comment]
@cenicoemir @rtarantelli Dá pra remover essa msg "O cadastro de novos usuários está desabilitado" ?
@cenicoemir @rtarantelli O que acontece com o esqueci minha senha, já que não configuramos o serviço de e-mail?

**Comment by cenicoemir** [comment]
@mergulhao No Painel administrativo dá para remover esse texto dos termos de uso, já apaguei, mas essa parte da english version ou o cadastro de novos usuários não é lá, vou procurar.

**Comment by mergulhao** [comment]
@cenicoemir Blz!

**Comment by cenicoemir** [comment]
Um pouco de XGH ou POG, mas consegui remover as informações ao menos até termos um layout novo para ela, apenas para registrar.
O "O cadastro de novos usuários está desabilitado" eu simplesmente removi esta frase o painel administrativo > Contas > inscrição.
Tanto o "Powered by..." e o English Version eu usei Custom CSS e adicionei um display: none as duas classes para ocultar da página.

**Comment by cenicoemir** [comment]
@mergulhao De qualquer forma, em relação aos Termos de Uso continuaremos a direcionar o Impulser para o que já temos no Notion ou vamos por dentro do rocket? No painel dá para por HTML com os termos.

**Comment by mergulhao** [comment]
@cenicoemir Show! Acho que os termos de uso podem ficar lá no app.impulso.network que já temos. Lá no rodapé do app.impulso.network fica o link pro notion com os termos. Já tá ok só lá mesmo.

Vi como ficou o resultado lá no chat.impulso.network. Tá bem ok.
