### ISSUE TITLE
Ui da Tela de Login do Rocket.Chat

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#133]

**Comment by brunomoch-zz** [comment]
https://xd.adobe.com/view/b1b37902-27f4-4eb4-47fd-73a19e4857cc-c782/

**Comment by cenicoemir** [comment]
UI de Login do Rocket.chat - https://xd.adobe.com/view/b1b37902-27f4-4eb4-47fd-73a19e4857cc-c782/screen/10ea17af-fe31-4d7e-a453-76fc0fa101ae/LOGIN-ROCKET-CHAT
