### ISSUE TITLE
Criar UI Mobile para Como Funciona

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#169]

**Comment by cenicoemir** [comment]
https://xd.adobe.com/spec/ec79ffb7-66f5-4d97-7e66-d797bd61fc43-9a48/screen/791faccd-f8ff-48b4-a830-779fb4515cdd/HOME-320px/

**Comment by brunomoch-zz** [comment]
atualizado:
https://xd.adobe.com/spec/e63da7ab-6d97-4092-559a-b02927624c33-900c/
