### ISSUE TITLE
Criar UI Mobile para Ranking Mensal/Geral

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#170]

**Comment by brunomoch-zz** [comment]
https://xd.adobe.com/spec/ec79ffb7-66f5-4d97-7e66-d797bd61fc43-9a48/screen/f4745247-2c70-4d44-a56d-6448b1ccad59/RANKING-320px/

**Comment by brunomoch-zz** [comment]
https://xd.adobe.com/spec/e63da7ab-6d97-4092-559a-b02927624c33-900c/
