### ISSUE TITLE
Criar UI Mobile para Dashboard/Perfil do Usuário

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#171]

**Comment by cenicoemir** [comment]
https://xd.adobe.com/spec/ec79ffb7-66f5-4d97-7e66-d797bd61fc43-9a48/screen/7be9157f-23f9-4894-b332-1a4b9ce769a7/HOME-320px-1/

**Comment by brunomoch-zz** [comment]
atualizado:
https://xd.adobe.com/spec/e63da7ab-6d97-4092-559a-b02927624c33-900c/
