### ISSUE TITLE
Implementar Mensagem de Boas Vindas da Atena

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#174]
Não existe uma introdução ao jogador a respeito do Atena quando ele entra no Rocket.Chat; esse recurso poderia aumentar o conhecimento a respeito da ferramenta e engajar o jogador nos objetivos do jogo; essa funcionalidade deve enviar uma mensagem privada ao jogador quando o mesmo entrar no rocket.chat pela primeira vez, esta mensagem deve conter informações a respeito das funcionalidades do jogo e direcionando o jogador para o site (http://atena.impulso.network).

Cenário Usuário do Game no Rocket.Chat

Dado que sou usuário do game
Quando entrar pela primeira vez no Rocket.Chat
Entao gostaria de poder receber uma mensagem de onboard sobre o Atena

**Comment by mvellasco** [comment]
Você poderia explicar melhor o que deve ser feito? Eu gostaria de contribuir com o projeto, e posso resolver esse issue!

**Comment by cenicoemir** [comment]
@mvellasco Vou adicionar a estória a descrição da issue em breve.

**Comment by cenicoemir** [comment]
Mensagem de Boas Vindas

Olá, Impulser! Eu sou **Atena**, deusa da sabedoria e guardiã deste reino! Se chegaste até aqui suponho que queiras juntar-se a nós, estou certa?! Vejo que tens potencial, mas terás que me provar que és capaz!

Em meus domínios terás que realizar tarefas para mim, teus feitos irão render-te **Pontos de Experiência** que, além de fortalecer-te, permitirão que obtenhas medalhas de **Conquistas** em forma de reconhecimento! Sou uma deusa amorosa, por isso saibas que, eventualmente, irei premiar-te de maneira especial!

No decorrer do tempo, sentirás a necessidade de acompanhar o teu progresso. Por isso, podes consultar os livros de nossa biblioteca que contém tudo o que fizestes até então, são eles:
- Pergaminhos de **Pontos de Experiência**: **!meuspontos** ou **/meuspontos**;
- e os Tomos de **Conquistas**: **!minhasconquistas** ou **/minhasconquistas**

Ah! Claro que não estás só na realização destas tarefas. Os nomes dos(as) Impulsers estão dispostos nos murais no exterior de meu templo, esta é uma forma de reconhecer o teu valor e os teusesforços. Lá, tu encontrarás dois murais: 
- O **!ranking** ou **/ranking** **Mensal** onde estão os nomes dos(das) que mais se esforçaram neste mês. Aquele(a) que estiver em primeiro lugar receberá uma recompensa especial;
- e o **!rakinggeral** ou **/rankinggeral** onde os nomes ficam dispostos, indicando -toda a sua contribuição realizada até o presente momento.

Sei que são muitas informações, mas tome nota, para que não te esqueças de nada. Neste papiro, encontrarás **tudo o que precisa** saber em caso de dúvidas:** http://atena.impulso.network. **

Espero que aproveite ao máximo **tua jornada** por aqui!
