### ISSUE TITLE
Implementar integração com o RD Station

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#183]

**Comment by lazaroalvarenga** [comment]
@cenicoemir precisamos de mais infos aqui. Qual será o mecanismo de ganho de pontos?

**Comment by cenicoemir** [comment]
Vou adicionar as informações a descrição, mas essa integração é para o lado do core para ter métricas da Atena.

**Comment by lazaroalvarenga** [comment]
https://developers.rdstation.com/pt-BR/overview
