### ISSUE TITLE
Update async-request references to the latest version

### ISSUE THREAD

**Issue by rtarantelli** [impulsoteam/atena#19]
3 vulnerabilities were found in the project.

**Moderate**        ReDoS via long string of semicolons
Package         tough-cookie
Patched in      >=2.3.0
Dependency of   async-request
Path            async-request > tough-cookie
More info       https://nodesecurity.io/advisories/130

**High**            Regular Expression Denial of Service
Package         tough-cookie
Patched in      >=2.3.3
Dependency of   async-request
Path            async-request > tough-cookie
More info       https://nodesecurity.io/advisories/525

**Low**             Prototype Pollution
Package         lodash
Patched in      >=4.17.5
Dependency of   async-request
Path            async-request > lodash
More info       https://nodesecurity.io/advisories/577

**Comment by cenicoemir** [comment]
Fechada em razão de Duplicidade com a issue #43
