### ISSUE TITLE
Criar UX/UI dos e-mails

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#215]

**Comment by brunomoch-zz** [comment]
o intuito foi ter uma pegada mais minimalista, alterando a cor de fundo pra dar um aspecto mais leve com relação as referências.

obs: não sei se é possível, mas seria interessante humanizar mais esses textos dos emails.

para aprovação:
https://xd.adobe.com/view/9cb11629-1ea2-4bc2-7c79-b73afee1c918-ea80/
