### ISSUE TITLE
Criar UX/UI da Mensagens Privadas com Usuários

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#217]

**Comment by brunomoch** [comment]
https://xd.adobe.com/view/95ee07f3-b2c8-4d0c-76f7-9c428ff4deb0-e3df/

**Comment by brunomoch-zz** [comment]
https://xd.adobe.com/spec/7d387e97-2b56-4e25-78fe-f47f5e0c01d5-0b09/
