### ISSUE TITLE
Filtrar Core Team do ranking

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#22]
Atualmente o ranking não está filtrando os Impulsers do core team. Esses Impulsers não devem aparecer no ranking.

- [ ] Listar todos os Impulsers do Core Team

**Comment by cenicoemir** [comment]
U7ZD2FCBB - Marcio Sena
U95LN062K - Claúdia
UCJA2A8Q5 - Emir
UB348CP6Z - Plinio
U83UZCDCM - Mira
UAXAVEF3M - Geisa
UB4J7597H - Art
UC7FJCL9G - Rebeca
UB2ELL480 - Thays
UAWNQHH38 - André
U89DXTF6W - Kari
UASHT1H7U - Amanda
UBV9QPYP9 - Maisa
UCS9EMKG9 - Fabiana

**Comment by lazaroalvarenga** [comment]
Depois que esta versão for pra produção por favor acessar **GET /resources/normalize** para setar a propriedade isCoreTeam para todos os usuários (que dali pra frente será required na model)

Criar o arquivo config/coreteam.yml como exemplo abaixo:

members:
  - U7ZD2FCBB
  - U95LN062K
  - UCJA2A8Q5
...
