### ISSUE TITLE
Criar UI/UX para tela de relatórios e ranking para impulsers de clientes

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#246]

**Comment by brunomoch-zz** [comment]
para aprovação:

https://xd.adobe.com/view/c23defea-1cb2-4854-641c-6e9458c9f131-b40c/

@cenicoemir @ofallante

**Comment by brunomoch-zz** [comment]
atualizado e adicionado o dashboard e resultado de busca:
https://xd.adobe.com/spec/32b7a6f8-2f7b-4903-581f-631e8fddeb9f-4486/
