### ISSUE TITLE
Criar APP oficial na conta do GitHub

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#248]

**Comment by mergulhao** [comment]
@cenicoemir Apps criadas.

@lazaroalvarenga @goldblade Já coloquei nos apps em var de ambiente o client_id e secret. As urls de callback são:

https://atena.impulso.network/auth/github/callback
https://staging.atena.impulso.network/auth/github/callback

O github não deixa cadastrar mais de uma url por app, então tiveram que ser apps separadas. Não criei pra localhost. Precisa criar ou vcs usam ae uma conta pessoal de vcs? Se precisar criar localhost tb, avisa ae.
