### ISSUE TITLE
Ranking exclusivo do core team

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#25]
Tendo em vista que os Impulsers do Core Team não aparecerão no **/ranking**. A fim de medir o desempenho e interações oferecer um **ranking particular** para esses usuários.

**Comment by ribeiroevandro** [comment]
@cenicoemir já temos a lista dos usuários do Core Team?

**Comment by ribeiroevandro** [comment]
Estou com essa tarefa

**Comment by lazaroalvarenga** [comment]
@ribeiroevandro não temos mas dá pra iniciar o tratamento com o Emir, Plínio, Mira, Geisa e André, por exemplo. afinal, precisam ser facilmente alteráveis como core team ou não. @marciovsena você entra nessa lista do core team?

**Comment by cenicoemir** [comment]
Cláudia e Rebeca também que sempre postam no #oportunidades, art e thays que eventualmente postam tb.

**Comment by ribeiroevandro** [comment]
O @marciovsena já me enviou a lista, estou vendo qual a melhor forma para fazer...

**Comment by cenicoemir** [comment]
Ótimo, eu tinha colado algumas em outra issue, mas o @marciovsena foi mais rápido, só agora percebi que dava para pegar diretamente do slack.

**Comment by lazaroalvarenga** [comment]
@ribeiroevandro bora marcar um pair pra fechar essa issue dentro desse sprint :D

**Comment by diegopolido** [comment]
de preferencia fazer isso num arquivo de configuração ou numa variável de ambiente (pra nao ficar hardcoded) :smile:

**Comment by lazaroalvarenga** [comment]
@diegopolido está! :D fiz com o @ribeiroevandro agora no fim da tarde num _pair programming_ e estamos usando para definir o membros do core team o arquivo `config/coreteam.yml`
