### ISSUE TITLE
Criar a UI para mensagem de boas vindas do Rocket.Chat

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#267]
Texto base:
OLÁ! AGRADECEMOS POR SE JUNTAR À IMPULSO NETWORK!

Você agora é um(a) Impulser! Sinta-se em casa!

A primeira dica que dou é visitar o nosso site de boas vindas! Lá você vai encontrar um conteúdo especial, explicando tudo o que acontece por aqui.
http://welcome.impulso.network/

Depois, se apresenta lá no canal #impulso-network pra todo mundo ficar sabendo que você tá na área.

Confere também o #welcome-meetup para participar do próximo meetup de boas vindas, conhecer novos(as) Impulsers e tirar suas dúvidas!!

Se, ainda assim, restar qualquer dúvida é só mandar no canal #duvidas ou me chama, mencionando @luiz!

Aproveite e divirta-se!

**Comment by brunomoch-zz** [comment]
link:
https://xd.adobe.com/spec/c2d16448-39d6-4ed2-6989-b75f88b686a5-b4e0/screen/8b534b21-54ae-4abd-87b5-20d7d1b7986b/BEM-VINDO-A-/
