### ISSUE TITLE
Revisar a interface do site da Atena

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#302]
Endereço: https://staging.atena.impulso.network

**Comment by brunomoch-zz** [comment]
![home-01](https://user-images.githubusercontent.com/45563339/55335737-0fd2f800-5472-11e9-88b0-9aba0022a2e2.jpg)
![home-02](https://user-images.githubusercontent.com/45563339/55335740-106b8e80-5472-11e9-9ea9-612c3db0dbf5.jpg)
![home-03](https://user-images.githubusercontent.com/45563339/55335741-106b8e80-5472-11e9-97d9-8f9e0aa7d418.jpg)
![home-04](https://user-images.githubusercontent.com/45563339/55335743-11042500-5472-11e9-9460-53d9abbdc13e.jpg)
![home-05](https://user-images.githubusercontent.com/45563339/55335744-119cbb80-5472-11e9-869f-1da415892b3b.jpg)
![ranking-01](https://user-images.githubusercontent.com/45563339/55335745-119cbb80-5472-11e9-818c-dceeeb9e9d49.jpg)





estou anexando algumas observações sobre o site da atena.

obs: algumas informações (como espaçamentos, por exemplo) com relação ao arquivo final do XP foram atualizadas no ui kit.

obs2: seguir as indicações do ui KIT ( https://xd.adobe.com/spec/cbceaf67-a64c-4467-74d8-9e982066b9c3-bdff/ )

obs3: eu não consegui acessar a tela de "login" e "conquistas"

**Comment by cenicoemir** [comment]
@goldblade @lazaroalvarenga @thaismartinsprojects verificar indicações ^

**Comment by cenicoemir** [comment]
Tarefa quebrada, verificar #339
