### ISSUE TITLE
Adicionar como interações aos graus de conquistas obtidos

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#321]
Foi verificado que a experiência obtida através do ganho de conquistas não está sendo adicionado ao ranking mensal. A correção deste bug é importante para que Impulsers que obtenham pontos através das conquistas e possam alcançar posições melhores no ranking mensal.

**Comment by goldblade** [comment]
@thaismartinsprojects nesse caso é interessante salvar a pontuação que a conquista gerou. tipo o score de cada interação que hj salvamos.
