### ISSUE TITLE
Criar Query para obtenção de indicador de quantidade de Impulsers que interagem mais de 6 vezes por semana.

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#329]
Não existe uma forma de mensurar Impulsers que realizam mais de 6 interações pontuáveis por semana, esta funcionalidade permitirá a mensuração desse indicador importante para uma das KRs da Impulso Network. A funcionalidade deve dispor de um end-point para integração com o Miner e um slashcommand para buscar a informação manualmente quando necessário.

**Comment by goldblade** [comment]
Criar endpoint para o miner consumir, add startDate e endDate, e team nos parametros

**Comment by cenicoemir** [comment]
https://github.com/impulsonetwork/atena/pull/372

**Comment by goldblade** [comment]
Exemplo de requisição para o miner

curl --request GET \
  --url http://localhost:4390/miner/mostactive \
  --header 'begin: 01-01-2019' \
  --header 'end: 14-04-2019' \
  --header 'team: ATENA' \
  --header 'token: ATENA' \
  --cookie connect.sid=s%253ALDb8TnvL9a1vw_Aj6oiwpLW0KPUjXxcq.GHY2xot0sLQwdvL%252Fq4QPtSVzdg7mtQ8bLR%252FB4Dcy1M0
