### ISSUE TITLE
Adicionar XP dos usuários do Slack aos usuários do Rocket.Chat

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#346]
Hoje os pontos de XP obtidos pelos usuários durante o MVP da Atena no slack não estão adicionados aos respectivos usuários do Rocket. Faz-se necessário adicionar esses pontos para perseverar o que foi feito durante este periodo.

**Comment by goldblade** [comment]
@cenicoemir para essa tarefa que acha de uma ui? imagino que precisamos escolher um usuario de origin de uma lista e um usuario de destino em outra lista. Depois mandar transferir os dados. Nessa pegada seria interassante já ter uma lista de usuarios no website onde podemos deletar ou editar dados. Sugiro fazer isso de forma bem crua agora e depois implementar isso na dashboard como o @brunomoch ta fazendo! ou se já tiver tela prevista de usuarios para isso, já implementar.

**Comment by cenicoemir** [comment]
Deixei comentário na issue

**Comment by cenicoemir** [comment]
Se acha que pode ficar mais simples desta forma podemos modificar a estória. Eu executo o trabalho sujo de ir dando o XP se for o caso.
