### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#42]
- [x] O que vamos usar? *Jest*

## O que foi Implementado:
- [x] `utils/calculateReceivedScore `

## O que falta Implementar:
- [x] Controller de Usuário
- [x] Controller de Interação
- [x] Model de Usuário
- [x] Model de Interação

**Comment by goldblade** [comment]
Bom dia, em que ponto ta essa discurssão? ontem brinquei um pouco com o código na parte de testes. Ainda muito no inicio usei aqui jest mesmo e a estutura de criar um diretorio __tests__ no raiz

no caso pro model user criei o arquivo

$ touch __tests__/models/user.spec.js

e o conteudo por enquanto assim
````
import User from "../../models/user";

describe("[Models] User", () => {
  it("should be invalid if name is empty", () => {
    let user = new User();
    user.validate(err => {
      expect(err.errors.name).toBeTruthy();
    });
    expect(user).toMatchSnapshot();
  });
});
`````

**Comment by rtarantelli** [comment]
É isso mesmo @goldblade segue nesta linha que estamos juntos!!!

**Comment by enieber** [comment]
Jest :+1:

**Comment by enieber** [comment]
usei jest para fazer o pr pois não precisa configurar nada para testes unitario.

**Comment by enieber** [comment]
@rtarantelli esta issue pode ser fechada?

**Comment by rtarantelli** [comment]
@enieber, vou mudar para closed, pois o objetivo principal era discutir qual framework utilizar e iniciar a implementação.

**Comment by lazaroalvarenga** [comment]
tios @rtarantelli e @enieber reabri a issue pra gente trackear nela os Testes implementados até englobarmos o código que já temos no app. Bele bele?

Pra não precisarmos criar duas issues muito próximas. :)
