### ISSUE TITLE
#5 Correção de vulnerabilidades encontradas no projeto

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#43]
Corrigir 3 vulnerabilidades no projeto, sendo uma crítica de DDOS.

**Moderate ReDoS via long string of semicolons**
Package tough-cookie
Patched in >=2.3.0
Dependency of async-request
Path async-request > tough-cookie
More info https://nodesecurity.io/advisories/130

**High Regular Expression Denial of Service**
Package tough-cookie
Patched in >=2.3.3
Dependency of async-request
Path async-request > tough-cookie
More info https://nodesecurity.io/advisories/525

**Low Prototype Pollution**
Package lodash
Patched in >=4.17.5
Dependency of async-request
Path async-request > lodash
More info https://nodesecurity.io/advisories/577

**Comment by lazaroalvarenga** [comment]
Para solucionar esse item estou criando o https://www.npmjs.com/package/make-requests :)
