### ISSUE TITLE
#3 Open-source - Pontuar: Issues, reviews e PR

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#45]
Ganho de XP: Issue: +1 de XP
Ganho de XP: Review: +1 de XP
Ganho de XP: PR: +3 de XP

**Comment by frankyston** [comment]
@cenicoemir poderia explicar melhor como é essa Issue?

Obrigado.

**Comment by lazaroalvarenga** [comment]
@frankyston qual a dúvida? :) 
Na prática cada issue criada aqui no GH === +1XP pro gamer, fazer review num PR também e enviar um PR darão +3XP

**Comment by cenicoemir** [comment]
É exatamente isso que o @lazaroalvarenga disse

**Comment by cenicoemir** [comment]
Fechando por duplicidade com #100
