### ISSUE TITLE
Implementar comando /checkpro @username para o Core Team verificar se o usuário e pro e a data de término

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#451]

**Comment by cenicoemir** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar comando /checkpro @username para o Core Team verificar se o usuário e pro e a data de término](https://trello.com/c/WaZi3QLy/101-implementar-comando-checkpro-username-para-o-core-team-verificar-se-o-usu%C3%A1rio-e-pro-e-a-data-de-t%C3%A9rmino)

**Comment by operfildoluiz** [comment]
Isso aquilo não vai rolar? :(

**Comment by cenicoemir** [comment]
@lhcgoncalves Em staging já funciona, quando fizermos deploy já vai estar ok.

**Comment by operfildoluiz** [comment]
Nice!

Em ter, 25 de jun de 2019 às 10:10, cenicoemir <notifications@github.com>
escreveu:
