### ISSUE TITLE
Refatoramento para nova arquitetura

### ISSUE THREAD

**Issue by thaismartins** [impulsoteam/atena#469]

**Comment by thaismartins** [comment]
Ajustar aplicação seguindo o modelo:
https://github.com/i0natan/nodebestpractices

**Comment by cenicoemir** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refatoramento para nova arquitetura](https://trello.com/c/z87r9vym/109-refatoramento-para-nova-arquitetura)
