### ISSUE TITLE
Implementar Inatividade

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#47]
Hoje quando um usuário fica inativo por determinado tempo, não é penalizado, assim não é possível saber se abandonou a comunidade e quão engajado está. Precisamos de um mecanismo para verificar a inativade do usuário após determinado tempo, para então reduzir os pontos do usuário, tornando o game mais competitivo.

**Cenário** Usuário do Game

**Dado** que sou usuário do game
**Quando** inativo por deteminado tempo
**Entao** o game passará a reduzir meus pontos dia a dia

**Cenário** Usuário do Game no Slack

**Dado** que sou usuário do game
**Quando** um dia antes de alcançado o período de inatividade
**Entao** o game enviará um alerta informando que meus pontos serão reduzidos no dia seguinte

**Cenário** Usuário do Game no Slack

**Dado** que sou usuário do game
**Quando** alcançado o período de inatividade
**Entao** reduzirá meus pontos reduzidos,
**E** o game enviará um alerta informando que meus pontos foram reduzidos

**Cenário** Usuário do Game no App Web

**Dado** que sou usuário do game no App Web
**Quando** clicar no meu perfil no App Web
**Entao** gostaria de visualizar o período de inatividade

**Cenário** Usuário do Core Team

**Dado** que sou usuário do Core Team
**Quando** clicar no perfil do usuário no App Web
**Entao** gostaria de visualizar o período de inatividade

**Cenário** Usuário do Core Team

**Dado** que sou usuário do Core Team
**Quando** selecionar o filtro usuários inativos no app web
**Entao** gostaria de visualizar todos os usuários em inatividade,
**E** o período de inatividade para cada usuário

Mecânica do game

- [x] Após 14 dias decrementar XP uma taxa de 1XP por dia.

**Comment by lazaroalvarenga** [comment]
Enviar mensagem pro usuário quando inativo

**Comment by lazaroalvarenga** [comment]
#82

**Comment by lazaroalvarenga** [comment]
#82
