### ISSUE TITLE
/rankingdocoreteam  Não exibe a lista de rankeados

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#51]
Verificar o caso de não exibição da lista de membros do Core Team através do /rankingdocoreteam . Prioridade baixa, priorizar outras issues.

**Comment by enieber** [comment]
o comando não seria [/coreteamranking](https://github.com/impulsonetwork/atena/blob/1abce56d1c50e7f831d80a9729e8803a7a2d7120/routes/bot.js#L72) ?

**Comment by lazaroalvarenga** [comment]
Na ultima call eu comentei que já tava resolvendo isso, não? :x

**Comment by cenicoemir** [comment]
Sim, mas eu disse que ia criar a issue e me esqueci kkk xD
