### ISSUE TITLE
Remover serviço de slash command

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#527]
Remover package com aplicação resposável por slash commands com `/` criado pelo Eduardo.

**Comment by goldblade** [comment]
seria remover no rocket?

**Comment by cenicoemir** [comment]
exato @goldblade pois não usamos mais comandos slash na atena.

**Comment by goldblade** [comment]
![WhatsApp Image 2019-08-29 at 21 30 16](https://user-images.githubusercontent.com/448205/63985097-5d48a500-caa4-11e9-92dd-0781a87bc575.jpeg)

tem que clicar em desinstalar ai em apps que deve resolver no rocket :D
