### ISSUE TITLE
Separar Reactions Positivos de Reactions Negativos

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#65]
Hoje os pontos de reações são exibidos juntos no perfil do usuário; não possiblitando uma análise mais detalhada para saber se este usuário é conhecido por suas reações negativas ou positivas, pois haverão conquistas associadas a estas duas reações.

Cenário 1

**Dado** que sou usuário do Core Team
**Quando** clicar no perfil do usuário no app Atena
**Entao** gostaria de poder visualizar reações positivas e negativa

**Comment by thaismartins** [comment]
Só serão contabilizadas como reactions:
- Positivas = Emoji de joinha para cima (description = "+1")
- Negativas = Emoji de joinha para baixo (description = "-1")

**Comment by thaismartins** [comment]
Adicionar outra propriedade `others` em reactions, que deverá receber as reactions antigas e as novas interações com o emoji da atena.
