### ISSUE TITLE
Blog - Implementar Pontuação por Postagens Realizadas e Comentários Realizados

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#77]
Implementar sistema para pontuação por eventos realizados no Blog Impulso (https://blog.impulso.network/) que deve contabilizar as Postagens e Comentários realizados. O blog utiliza o wordpress para postagens e https://disqus.com/ como ferramenta de controle para de comentários.

**Valores em XP para eventos**
- [ ] Postagens realizadas: 5XP;
- [ ] Comentários realizados: 1XP;

**Comment by lazaroalvarenga** [comment]
urls da api do wp:

Posts recentes: https://blog.impulso.network/wp-json/wp/v2/posts
Detalhes de um Autor: https://blog.impulso.network/wp-json/wp/v2/users/14

**Comment by cenicoemir** [comment]
Issue em duplicidade com Issue #98 , fechando esta.
