### ISSUE TITLE
Formatação nos pontos do ranking /meuspontos

### ISSUE THREAD

**Issue by goldblade** [impulsoteam/atena#79]
Percebi que na apresentação do meus pontos temos um problema de exibição por causa da divisão de ponto flutuante.

Exemplo: Olá Eduardo Junior, atualmente você está no nível 1 com 61.300000000000004 XP

**Comment by lazaroalvarenga** [comment]
@goldblade botamos uma "solução" (https://github.com/impulsonetwork/atena/blob/e439371e8511e18d9d9228920c361dbdf5aaca34/controllers/user.js#L105) pra isso que vai subir nesse release do fds mas aceitamos uma sugestão mais elegante :)

**Comment by goldblade** [comment]
Bom não sei se é mais elegante mas é uma sugestão
result.score = result.score.toFixed(1);
or 
result.score = result.score.toFixed(2);

**Comment by lazaroalvarenga** [comment]
Manda um PR sugerindo, tio! :D

**Comment by goldblade** [comment]
pode deixar.. procurando um tempo aqui de sobra, mas mando sim 🚀

**Comment by rtarantelli** [comment]
Este item foi corrigido no PR #80
