### ISSUE TITLE
Imagem quebra depois de atualizada no Slack

### ISSUE THREAD

**Issue by rtarantelli** [impulsoteam/atena#89]
Depois de atualizar a imagem no Slack ela aparece quebrada no perfil do usuário como pode ver na imagem abaixo:

![image](https://user-images.githubusercontent.com/31748448/49401686-08534a80-f72f-11e8-8193-aa6a22a60c21.png)

**Comment by lazaroalvarenga** [comment]
Vamos continuar precisando armazenar esta imagem?

**Comment by rtarantelli** [comment]
Hoje consideramos a imagem do Slack. Devemos considerar de outra fonte. @cenicoemir de onde podemos passar a considerar o avatar do usuário?

**Comment by pliniopcc** [comment]
Podemos tentar seguir a mesma lógica que temos para o sistema interno da Impulso: primeiro pegamos a do linkedin, se não tiver > pegamos do slack, se não tiver > pegamos do gravatar > se não tiver, colocamos um avatar genérico

**Comment by lazaroalvarenga** [comment]
vou fechar essa issue já que o armazenamento desta imagem não será mais com a Atena.
