### ISSUE TITLE
Pesquisa sobre consumo da API do Rocket.chat

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#97]

**Comment by lazaroalvarenga** [comment]
a Rest API deles está em WIP ainda mas já tem as funcionalidades que precisamos com https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage/

Tem um SDK também mas pelos testes iniciais não funciona tão bem quanto deveria https://github.com/RocketChat/Rocket.Chat.js.SDK

**Comment by mergulhao** [comment]
- [ ] Mensagem enviada
- [ ] Mensagem respondida (thread)
- [ ] Reação dada
- [ ] Reação recebida
